apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: my-app-namespace # Add a specific namespace here
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
