name: Feature request
description: Suggest a new feature or enhancement
title: '[FEATURE]: '
labels: ['feature request', 'enhancement', 'priority/low']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request, your contribution is invaluable in helping us improve the quality and reliability of repository.
  - type: markdown
    attributes:
      value: |
        Before you begin, please make sure you've checked if the feature has already been asked, if you find a similar request, feel free to add any additional information or context that may help us resolve it more effectively.
  - type: input
    id: contact
    attributes:
      label: Contact details
      description: If possible, write down the contact information for this feature request. If you need additional communication, if you want contact via “github”, leave this field blank.
      placeholder: example@domain.com
  - type: textarea
    id: what-wanted
    attributes:
      label: What the essence of your feature request
      description: And tell the maintainers, what can you provide for a solution for this request.
      placeholder: Write that form, tell us what you want!
      value: ...
    validations:
      required: true
  - type: dropdown
    id: OS
    attributes:
      label: On what OS you want to maintain your request.
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
        - Mobile (specify)
        - Not important
  - type: checkboxes
    id: terms
    attributes:
      label: Code of conduct
      description: By submitting this feature request, you agree to follow our code of conduct.
      options:
        - label: I agree to follow this project's code of conduct
          required: true
  - type: checkboxes
    id: issue-policy
    attributes:
      label: Issue policy
      description: By submitting this feature request, you agree to follow our issue policy.
      options:
        - label: I agree to follow this project's issue policy
          required: true
  - type: checkboxes
    id: security-policy
    attributes:
      label: Security policy
      description: By submitting this feature request, you agree to follow our security policy.
      options:
        - label: I agree to follow this project's security policy.
          required: true
